### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by AcarBurak** [ec1oud/grefsen#1]
Under pure Qt 5.7 Arch system:

```
/usr/lib/qt/bin/rcc -name grefsen grefsen.qrc -o .rcc/qrc_grefsen.cpp
RCC: Error in 'grefsen.qrc': Cannot find file 'fonts/FontAwesome.otf'
make[1]: *** [Makefile:519: .rcc/qrc_grefsen.cpp] Error 1
make[1]: Leaving directory '/home/burak/bin/grefsen/compositor'
make: *** [Makefile:45: sub-compositor-make_first] Error 2
```

Installing [otf-font-awesome](https://aur.archlinux.org/packages/otf-font-awesome/) doesn't make a difference.

**Comment by trilean** [comment]
You have to run
```
git submodule init
git submodule update
```
as Font Awesome is part of the repo.

**Comment by ec1oud** [comment]
Yep.

If I was making an arch package, maybe it should just depend on FontAwesome rather than having a resource.  Or maybe some day it will be a reasonable assumption that everybody has this font.  Meanwhile I figured having it as a resource improves portability.
