### ISSUE TITLE
seg faults with undefined symbol

### ISSUE THREAD

**Issue by je-vv** [ec1oud/grefsen#11]
% ./grefsen 
qt5ct: using qt5ct plugin
Screen "eDP-1" QRect(0,0 1920x1080) QSizeF(309, 173) DPI: log 96.1263 phys 158.196
Screen "DP-1-1" QRect(0,0 1920x1080) QSizeF(509, 286) DPI: log 96.1263 phys 95.8637
QQmlApplicationEngine failed to load component
qrc:///qml/main.qml:29 Type Screen unavailable
qrc:///qml/Screen.qml:22 plugin cannot be loaded for module "Grefsen": Cannot load library /home/vasqueja/.pkgs/src/grefsen/grefsen/imports/Grefsen/libgrefsenplugin.so.1.0.0: (/home/vasqueja/.pkgs/src/grefsen/grefsen/imports/Grefsen/libgrefsenplugin.so.1.0.0: undefined symbol: _ZN13LauncherModel15allApplicationsEv)

Segmentation fault (core dumped)

+++++

Under gdb:

(gdb) r
Starting program: /home/vasqueja/.pkgs/src/grefsen/grefsen/grefsen 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeb25c700 (LWP 1927)]
qt5ct: using qt5ct plugin
Screen "eDP-1" QRect(0,0 1920x1080) QSizeF(309, 173) DPI: log 96.1263 phys 158.196
Screen "DP-1-1" QRect(0,0 1920x1080) QSizeF(509, 286) DPI: log 96.1263 phys 95.8637
[New Thread 0x7fffe28ab700 (LWP 1928)]
QQmlApplicationEngine failed to load component
qrc:///qml/main.qml:29 Type Screen unavailable
qrc:///qml/Screen.qml:22 plugin cannot be loaded for module "Grefsen": Cannot load library /home/vasqueja/.pkgs/src/grefsen/grefsen/imports/Grefsen/libgrefsenplugin.so.1.0.0: (/home/vasqueja/.pkgs/src/grefsen/grefsen/imports/Grefsen/libgrefsenplugin.so.1.0.0: undefined symbol: _ZN13LauncherModel15allApplicationsEv)

Thread 1 "grefsen" received signal SIGSEGV, Segmentation fault.
0x00007ffff65fbcfa in QObject::setProperty(char const*, QVariant const&) () from /usr/lib/libQt5Core.so.5
(gdb) bt full
#0  0x00007ffff65fbcfa in QObject::setProperty(char const*, QVariant const&) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#1  0x000055555555ab1f in main ()
No symbol table info available.

++++

Using Arch up to date, with following packages:

qt5-base 5.9.2-1 (qt qt5)
qt5-declarative 5.9.2-1 (qt qt5)
qt5-wayland 5.9.2-1 (qt qt5)
qt5-quickcontrols 5.9.2-1 (qt qt5)
qt5-quickcontrols2 5.9.2-2 (qt qt5)
libqtxdg 3.1.0-1

**Comment by ec1oud** [comment]
Fixed.  Not sure why that was not a problem before... but it was certainly un-implemented.
