### ISSUE TITLE
Unable to clone grefsen submodules

### ISSUE THREAD

**Issue by hexanet67** [ec1oud/grefsen#13]
Hi, I'm trying to build grefsen.
git clone  https://github.com/ec1oud/grefsen.git  pass without problems

but git submodule update --init --recursive fails with following messages...

Cloning into '/home/jan/Devel/grefsen/thirdparty/qt-tuio-sender'...
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ec1oud/qt-tuio-sender.git' into submodule path '/home/jan/Devel/grefsen/thirdparty/qt-tuio-sender' failed
Failed to clone 'thirdparty/qt-tuio-sender'. Retry scheduled
Cloning into '/home/jan/Devel/grefsen/thirdparty/qt-tuio-sender'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ec1oud/qt-tuio-sender.git' into submodule path '/home/jan/Devel/grefsen/thirdparty/qt-tuio-sender' failed
Failed to clone 'thirdparty/qt-tuio-sender' a second time, aborting

What I am missing or doing wrong ?
Please let me know.
Best regards,
   Jan

**Comment by ec1oud** [comment]
You could do without that anyway, but good point... might as well use https instead of git protocol, because for the latter you need to be authenticated with github.  So now you can pull and try again.
