### ISSUE TITLE
No mouse cursor when started from a tty

### ISSUE THREAD

**Issue by alive4ever** [ec1oud/grefsen#3]
Following the instructions on `README.md`, I've successfully built `grefsen`. Manually downloading and putting `FontAwesome.otf` into `./thirdparty/Font-Awesome/fonts` is required for successful build. This information should be added to `README.md`.

Launching `grefsen` inside X11 session as window works great. As soon as I switch to tty and launch directly with `QT_QPA_PLATFORM=eglfs`, I can't get mouse cursor to interact with grefsen launcher. In this state, I can't do anything inside `grefsen`, not even pressing `ctrl+alt+backspace` to quit. I had to press power button to end it all.

It would be better to show mouse cursor when launched from tty, so that it's usable as standalone desktop environment.

**Comment by ec1oud** [comment]
That's a Qt thing not a grefsen thing: it tends to come up (especially in pre-5.6 versions) when you run Qt any program on the console using the eglfs plugin.  (I bet if you run any other Qt program you'll have the same problem.  You can give `-plugin eglfs` to anything.)  Originally eglfs was considered to be only for embedded systems, so there wasn't an expectation that it would "just work" on a typical desktop without configuration and customization.  Now that plugin has plugins of its own, and you can also choose between various input plugins.  For example these startup parameters:

`-plugin EvdevTouch -plugin EvdevMouse -plugin EvdevTablet -plugin EvdevKeyboard`

or,

`-plugin libinput`

But libinput is getting popular to replace direct use of evdev everywhere, including in Qt.  It's supposed to be the default already after https://codereview.qt-project.org/#/c/123584/ so if you had it available when you built Qt, it should have been detected and used as the default, and then you shouldn't need to load the plugin manually.  But you still can if you need to, as a workaround.

You can also turn on the qt.qpa.* logging categories to help troubleshoot.
