### ISSUE TITLE
Segfault on start under Arch Linux

### ISSUE THREAD

**Issue by tidux** [ec1oud/grefsen#5]
Terminal output here:

```
./grefsen -w
Screen "eDP1" QRect(0,0 1920x1080) QSizeF(340, 190) DPI: log 96.1263 phys 143.907
failed to load Manzanita font from resources
grefsen.registration: Grefsen
grefsen.registration: Grefsen
theme is "oxygen" paths ("/home/jon/.icons", "/usr/local/share/icons", "/usr/share/icons", "/usr/share/pixmaps", ":/icons") default icon "application-x-executable"
QQmlApplicationEngine failed to load component
qrc:///qml/main.qml:54 XdgShellV5 is not a type

zsh: segmentation fault (core dumped)  ./grefsen -w
```

**Comment by johanhelsing** [comment]
qrc:///qml/main.qml:54 XdgShellV5 is not a type

My guess would be that you're running qtwayland 5.7 (the tech preview) while grefsen requires 5.8 (releases soon, but you can get the rc). A lot of components changed names, including XdgShell.

**Comment by ec1oud** [comment]
Exactly.  Like the README says:

Qt 5.8 (if you need 5.7, use the 5.7 branch)

Would be nice if I can find a way to have a better error message instead of segfaulting though.
