### ISSUE TITLE
Embedded X Server

### ISSUE THREAD

**Issue by juanlatorre** [ec1oud/grefsen#9]
Hi grefsen, you said that is possible to embed an X server, i'm currently developing a Qt / Wayland WM as well, and that point is my bottleneck.

How exactly is embedding an X server possible?

Thanks for your time m8, awesome work here.

**Comment by ec1oud** [comment]
I think it's possible because Weston does it, that's all.  I haven't studied exactly how.

Grefsen is the project name, not my name.  It's also the name of a hill in Oslo.

**Comment by juanlatorre** [comment]
Holy cow, i'm sorry ec1oud, and thanks for the info! I'll keep researching; also if i find a way to do it i'll tell ya'.
